trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: "Setup"
  inputs:
    versionSource: 'spec'
    versionSpec: '12.x'

- script: 'npm install'
  displayName: "Instala dependências"

- script: 'npm run test'
  displayName: "Executa os testes"


