name: End-to-end tests 🧪

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run end-to-end tests on desktop viewport 💻
        uses: cypress-io/github-action@v2
        with:
          command: npm test

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          branch: gh-pages  # Ensure this matches your target branch
