name: Testes de ponta a ponta 🧪

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Executar testes 💻
        uses: cypress-io/github-action@v2
        with:
          command: npm test

      - name: Publicar relatório
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Use o PAT armazenado como segredo
          publish_dir: ./mochawesome-report
